// src/routes/truth-table/components/table.svelte
<script lang="ts">
	import type {ParsedTable} from '@lusc/truth-table';

	export let table: ParsedTable;
</script>

<table>
	<thead>
		<tr>
			{#each table.columns as col (col)}
				<th>{col}</th>
			{/each}
		</tr>
	</thead>
	<tbody>
		{#each table.rows as row (row.join('-'))}
			<tr>
				{#each row as cell, index (cell ? index : -index)}
					<td class:cell_true={cell} class:cell_false={!cell}>
						{cell}
					</td>
				{/each}
			</tr>
		{/each}
	</tbody>
</table>

<style>
	table {
		table-layout: fixed;
		width: max-content;
	}

	tr {
		border-bottom: var(--table-border);
	}

	td.cell_false {
		color: var(--red);
	}
	td.cell_true {
		color: var(--green);
	}

	th,
	td {
		padding: 4px 1em;

		border-left: var(--table-border);
	}
	th:first-child,
	td:first-child {
		border-left: none;
	}
</style>

// src/truth-table/components/table.tsx
import clsx from 'clsx';
import React from 'react';
import styled from 'styled-components';
import {ParsedTable} from '@lusc/truth-table';

const StyledTable = styled.table`
	table-layout: fixed;
	width: max-content;

	tr {
		border-bottom: var(--table-border);
	}

	td {
		&.cell_false {
			color: var(--red);
		}
		&.cell_true {
			color: var(--green);
		}
	}

	th,
	td {
		padding: 4px 1em;

		border-left: var(--table-border);
		&:first-child {
			border-left: none;
		}
	}
`;

export const Table: React.FC<{table: ParsedTable}> = ({table}) => (
	<StyledTable>
		<thead>
			<tr>
				{table.columns.map(col => (
					<th key={col}>{col}</th>
				))}
			</tr>
		</thead>
		<tbody>
			{table.rows.map(row => (
				<tr key={row.join('-')}>
					{row.map((cell, index) => (
						<td
							key={cell ? index : -index}
							className={clsx({
								cell_true: cell,
								cell_false: !cell,
							})}
						>
							{String(cell)}
						</td>
					))}
				</tr>
			))}
		</tbody>
	</StyledTable>
);
