// src/quick-faker/components/modules/commerce.svelte
<script lang="ts">
	import {faker} from '@faker-js/faker';

	import Module from '../module.svelte';
</script>

<Module
	title="Commerce"
	module={faker.commerce}
	keys={[
		'department',
		'price',
		'product',
		'productAdjective',
		'productDescription',
		'productMaterial',
		'productName',

		// Deprecated
		// 'color',
	]}
/>

// src/quick-faker/components/modules/commerce.tsx
import {faker} from '@faker-js/faker';
import React from 'react';

import {Module} from '../module';

export const Commerce: React.FC = () => (
	<Module
		title='Commerce'
		module={faker.commerce}
		keys={[
			'department',
			'price',
			'product',
			'productAdjective',
			'productDescription',
			'productMaterial',
			'productName',

			// Deprecated
			// 'color',
		]}
	/>
);
