// src/quick-faker/components/modules/system.svelte
<script lang="ts">
	import {faker} from '@faker-js/faker';

	import Module from '../module.svelte';
</script>

<Module
	title="System"
	module={faker.system}
	keys={[
		'commonFileExt',
		'commonFileName',
		'commonFileType',
		'cron',
		'directoryPath',
		'fileExt',
		'fileName',
		'filePath',
		'fileType',
		'mimeType',
		'networkInterface',
		'semver',
	]}
/>

// src/quick-faker/components/modules/system.tsx
import {faker} from '@faker-js/faker';
import React from 'react';

import {Module} from '../module';

export const System: React.FC = () => (
	<Module
		title='System'
		module={faker.system}
		keys={[
			'commonFileExt',
			'commonFileName',
			'commonFileType',
			'cron',
			'directoryPath',
			'fileExt',
			'fileName',
			'filePath',
			'fileType',
			'mimeType',
			'networkInterface',
			'semver',
		]}
	/>
);
