// src/index/components/projects.tsx
import React, {useEffect} from 'react';

import projects_ from '../projects.json';
import '../styles/projects.scss';

type ProjectType = (
	| {
			type: 'anchor';
			href: string;
			short_description: string;
			description: string;
	  }
	| {
			type: 'title';
	  }
) & {
	key: string;
	text: string;
};
type ProjectsType = ProjectType[];

const projects = projects_ as ProjectsType;

const Project: React.FC<{
	project: ProjectType;
}> = ({project}) => {
	const {text, key} = project;

	const id = `#${key}`;

	if (project.type === 'title') {
		return (
			<div className="project-row title">
				<a href={id} className="id-anchor">
					#
				</a>
				<h1 id={key}>{text}</h1>
			</div>
		);
	}

	const {href, description} = project;

	return (
		<div className="project-row">
			<a href={id} className="id-anchor">
				#
			</a>
			<div className="project" id={key}>
				<a href={href}>{text}</a>
				<div>{description}</div>
				<div />
			</div>
		</div>
	);
};

export const Projects: React.FC = () => {
	useEffect(() => {
		if (location.hash) {
			try {
				document.querySelector(location.hash)?.scrollIntoView();
			} catch (error: unknown) {
				console.error(error);
			}
		}
	}, []);

	return (
		<div className="projects">
			{projects.map(project => (
				<Project key={project.key} project={project} />
			))}
		</div>
	);
};

// src/routes/index/components/projects.svelte
<script lang="ts">
	import {onMount} from 'svelte';

	import type {Project} from '../project.d.ts';
	import projects_ from '../projects.json';

	import SingleProject from './single-project.svelte';

	const projects = projects_ as readonly Project[];

	onMount(() => {
		if (location.hash) {
			try {
				document.querySelector(location.hash)?.scrollIntoView();
			} catch (error: unknown) {
				console.error(error);
			}
		}
	});
</script>

<main>
	<div class="projects">
		{#each projects as project (project.key)}
			<SingleProject {project} />
		{/each}
	</div>
</main>

<style lang="scss">
	@use 'sass:color';

	main {
		display: flex !important;
		justify-content: center;
		/* Margin would seem more appropriate but on mobile the background color doesn't apply to that section */
		padding: 2em 0;
	}

	.projects {
		display: flex;
		flex-direction: column;
		gap: 2em;

		width: 50vw;
	}

	@media (max-width: 500px) {
		.projects {
			width: 95vw;
			display: flex;
			flex-direction: column;
		}
	}
</style>
