// src/fake-fitness-app/components/help.svelte
<div class="help">
	<div class="help-text">
		Using Firefox? Use{' '}
		<code>{":screenshot --dpr <number> --selector '.fake-app'"}</code>{' '}
		in the web console
	</div>
</div>

<style>
	.help {
		color: var(--text-white);

		grid-column: 3 / 4;

		margin: 2em;
	}

	code {
		background-color: var(--code-background);
		padding: 0.2em;
		border-radius: 3px;
	}
</style>

// src/fake-fitness-app/components/help.tsx
import React from 'react';

import '../styles/help.scss';

const Help: React.FC = () => (
	<div className='help'>
		<div className='help-text'>
			Using Firefox? Use{' '}
			<code>
				:screenshot --dpr &lt;number&gt; --selector &apos;.fake-app&apos;
			</code>{' '}
			in the web console
		</div>
	</div>
);

export default Help;
