// src/fake-fitness-app/components/main-app-date-time.svelte
<script context="module" lang="ts">
	import dayjs from 'dayjs';
	import customParseFormat from 'dayjs/plugin/customParseFormat';
	dayjs.extend(customParseFormat);

	const dateAtLoad = dayjs().format('D MMM');
	const timeAtLoad = dayjs().format('HH:mm');
</script>

<script lang="ts">
	import TimeInput from './time-input.svelte';

	import {
		calcDurationSecondsSinceMidnight,
		dateValid,
		timeValid,
		toDate,
		toTime,
	} from '../util';

	export let duration: string;
	let date = dateAtLoad;
	let timeFrom = timeAtLoad;

	$: durationTimeSinceMidnightInSeconds =
		calcDurationSecondsSinceMidnight(duration);
</script>

<div class="main-app-date-time">
	<div class="day-date-inputs">
		<span
			>{#if dateValid(date)}{toDate(date).format('ddd, ')}{/if}</span
		>
		<input
			class="input-remove-input-visuals"
			class:invalid={!dateValid(date)}
			bind:value={date}
			on:input={event => {
				const input = event.currentTarget.value;
				date = dateValid(input) ? toDate(input).format('D MMM') : input;
			}}
		/>
	</div>
	<div class="time-inputs">
		<TimeInput bind:time={timeFrom} width="5ch" />
		<span>
			{'-  '}{#if timeValid(timeFrom) && durationTimeSinceMidnightInSeconds !== false}{toTime(
					timeFrom,
				)
					.add(durationTimeSinceMidnightInSeconds, 's')
					.format('HH:mm')}{/if}
		</span>
	</div>
</div>

<style>
	.main-app-date-time {
		color: var(--text-white);

		display: flex;
		flex-direction: column;
		align-items: flex-start;

		margin: 0 6.5%;
		margin-top: 0.75em;
		font-size: 0.9em;
	}

	.day-date-inputs {
		display: flex;
	}

	.day-date-inputs span {
		white-space: pre;
	}

	.time-inputs {
		display: flex;
		margin-top: 0.3em;
	}
	.time-inputs span {
		/* Looks more centered this way */
		margin: 0 3px 0 1px;
	}
</style>

// src/fake-fitness-app/components/main-app-date-time.tsx
import React, {useState} from 'react';
import * as dayjs from 'dayjs';
import * as customParseFormat from 'dayjs/plugin/customParseFormat';
import clsx from 'clsx';

import '../styles/main-app-date-time.scss';

import {
	calcDurationSecondsSinceMidnight,
	dateValid,
	timeValid,
	toDate,
	toTime,
} from '../scripts/date-functions';
import TimeInput from './time-input';

dayjs.extend(customParseFormat);

const dateAtLoad = dayjs().format('D MMM');

const MainAppDateTime: React.FC<{
	duration: string;
}> = ({duration}) => {
	const [dateValue, setDate] = useState(dateAtLoad);

	const [timeFrom, setTimeFrom] = useState(dayjs().format('HH:mm'));

	const handleDateInput: React.FormEventHandler<HTMLInputElement> = event_ => {
		const value = event_.currentTarget.value;

		if (dateValid(value)) {
			setDate(toDate(value).format('D MMM'));
		} else {
			setDate(value);
		}
	};

	const durationTimeSinceMidnightInSeconds
		= calcDurationSecondsSinceMidnight(duration);

	return (
		<div className="main-app-date-time">
			<div className="day-date-inputs">
				<span>{dateValid(dateValue) && toDate(dateValue).format('ddd, ')}</span>
				<input
					className={clsx('input-remove-input-visuals', {
						invalid: !dateValid(dateValue),
					})}
					value={dateValue}
					onInput={handleDateInput}
				/>
			</div>
			<div className="time-inputs">
				<TimeInput setTime={setTimeFrom} />
				<span>
					{'-  '}
					{timeValid(timeFrom)
						&& durationTimeSinceMidnightInSeconds !== false
						&& toTime(timeFrom)
							.add(durationTimeSinceMidnightInSeconds, 's')
							.format('HH:mm')}
				</span>
			</div>
		</div>
	);
};

export default MainAppDateTime;
