// src/routes/fake-fitness-app/components/workout-details.svelte
<script lang="ts">
	import * as CONSTS from '../consts.ts';
	import {isValidDuration, parseDuration, toSpeed} from '../util.ts';

	import Run from './icons/run.svelte';

	const {duration, distance}: {duration: string; distance: string} = $props();
	let totalDuration = $state(CONSTS.duration);
	let maxSpeed = $state('0.0');

	function onDurationInput(event: {currentTarget: HTMLInputElement}): void {
		const value = event.currentTarget.value;
		totalDuration = isValidDuration(value)
			? parseDuration(value).format('HH:mm:ss')
			: value.trim();
	}
</script>

<div class="workout-details">
	<div class="workout-details-title">Workout details</div>
	<div class="table">
		<div class="row">
			<div>
				<div class="table-value">{duration}</div>
				<div class="table-explanation">Workout duration</div>
			</div>
			<div class="vertical-border height-22"></div>
			<div>
				<input
					class="input-remove-input-visuals table-value"
					class:invalid={!isValidDuration(totalDuration)}
					value={totalDuration}
					placeholder="HH:mm:ss"
					oninput={onDurationInput}
				/>
				<div class="table-explanation">Total duration</div>
			</div>
		</div>
		<hr />
		<div class="row">
			<div>
				<div class="table-value">{distance}</div>
				<div class="table-explanation">Distance(km)</div>
			</div>
			<div class="vertical-border height-22"></div>
			<div>
				<Run />
			</div>
		</div>
		<hr />
		<div class="row">
			<div>
				<div class="table-value">{toSpeed(duration, distance) || ''}</div>
				<div class="table-explanation">Avg. speed(km/h)</div>
			</div>
			<div class="vertical-border height-22"></div>
			<div>
				<input
					class="input-remove-input-visuals table-value"
					class:invalid={!CONSTS.speedRegex.test(maxSpeed)}
					bind:value={maxSpeed}
					placeholder="0.0"
				/>
				<div class="table-explanation">Max. speed(km/h)</div>
			</div>
		</div>
	</div>
</div>

<style>
	.workout-details {
		color: var(--text-white);

		background: var(--card-background);
		border-radius: var(--card-border-radius);

		display: flex;
		justify-content: center;
		flex-direction: column;

		margin-top: 2.8vmin;
		padding: 2.5vmin 3.4vmin;
	}

	.workout-details-title {
		margin-bottom: 1em;
	}

	.table {
		display: flex;
		flex-direction: column;
		justify-content: center;
	}

	.table :global(svg) {
		height: 1.5em;
	}

	.table :global(hr) {
		width: 100%;
		border: none;
		border-bottom: 1px solid var(--border-color);
	}
	.table :global(.vertical-border) {
		color: var(--border-color);
	}

	.table-value,
	.table-explanation {
		text-align: center;
		width: 100%;
	}

	.row {
		display: grid;
		grid-template-columns: minmax(0, 1fr) 1px minmax(0, 1fr);
		align-items: center;
	}

	.row > div {
		display: flex;
		align-items: center;
		flex-direction: column;
	}

	.table-explanation {
		font-size: 0.7em;
		color: var(--table-small-explanation);
	}
</style>

// src/fake-fitness-app/components/workout-details.tsx
import clsx from 'clsx';
import React, {useState} from 'react';

import * as CONSTS from '../scripts/consts';
import {
	calcDurationSecondsSinceMidnight,
	isValidDuration,
	parseDuration,
} from '../scripts/date-functions';
import {ReactComponent as Run} from '../icons/run.svg';

import '../styles/workout-details.scss';

const toSpeed = (duration: string, distance: string): string | false => {
	const durationInSeconds = calcDurationSecondsSinceMidnight(duration);

	if (durationInSeconds === false) {
		return false;
	}

	if (!CONSTS.distanceRegex.test(distance)) {
		return false;
	}

	if (durationInSeconds === 0) {
		// Avoid division by 0
		return '0.0';
	}

	const parsedDistanceInMeters = Number(distance) * 1000;

	const speedInMetersPerSecond = parsedDistanceInMeters / durationInSeconds;

	return (speedInMetersPerSecond * 3.6).toFixed(1);
};

const WorkoutDetails: React.FC<{duration: string; distance: string}> = ({
	duration,
	distance,
}) => {
	const [totalDuration, setTotalDuration] = useState(CONSTS.duration);
	const [maxSpeed, setMaxSpeed] = useState('0.0');

	return (
		<div className='workout-details'>
			<div className='workout-details-title'>Workout details</div>
			<div className='table'>
				<div className='row'>
					<div>
						<div className='table-value'>{duration}</div>
						<div className='table-explanation'>Workout duration</div>
					</div>
					<div className='vertical-border height-22' />
					<div>
						<input
							className={clsx(
								'input-remove-input-visuals',
								{
									invalid: !isValidDuration(totalDuration),
								},
								'table-value',
							)}
							value={totalDuration}
							placeholder='HH:mm:ss'
							onInput={(event_): void => {
								const value = event_.currentTarget.value;

								setTotalDuration(
									isValidDuration(value)
										? parseDuration(value).format('HH:mm:ss')
										: value.trim(),
								);
							}}
						/>
						<div className='table-explanation'>Total duration</div>
					</div>
				</div>
				<hr />
				<div className='row'>
					<div>
						<div className='table-value'>{distance}</div>
						<div className='table-explanation'>Distance(km)</div>
					</div>
					<div className='vertical-border height-22' />
					<div>
						<Run />
					</div>
				</div>
				<hr />
				<div className='row'>
					<div>
						<div className='table-value'>{toSpeed(duration, distance)}</div>
						<div className='table-explanation'>Avg. speed(km/h)</div>
					</div>
					<div className='vertical-border height-22' />
					<div>
						<input
							className={clsx('input-remove-input-visuals', 'table-value', {
								invalid: !CONSTS.speedRegex.test(maxSpeed),
							})}
							value={maxSpeed}
							placeholder='0.0'
							onInput={(event_): void => {
								const value = event_.currentTarget.value.trim();
								setMaxSpeed(value);
							}}
						/>
						<div className='table-explanation'>Max. speed(km/h)</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default WorkoutDetails;
