// src/fake-fitness-app/components/time-input.tsx
import clsx from 'clsx';
import * as dayjs from 'dayjs';
import * as customParseFormat from 'dayjs/plugin/customParseFormat';
import React, {useState} from 'react';

import {timeValid, toTime} from '../scripts/date-functions';

dayjs.extend(customParseFormat);

const timeAtLoad = dayjs().format('HH:mm');

const TimeInput: React.FC<{
	className?: string[] | string;
	setTime?: React.Dispatch<React.SetStateAction<string>>;
}> = ({className, setTime: parentSetTime}) => {
	const [time, setTime] = useState(timeAtLoad);

	const handleTimeInput: React.FormEventHandler<HTMLInputElement> = event_ => {
		const value = event_.currentTarget.value;

		const stateValue = timeValid(value) ? toTime(value).format('HH:mm') : value;

		setTime(stateValue);
		parentSetTime?.(stateValue);
	};

	return (
		<input
			className={clsx(
				'input-remove-input-visuals',
				{
					invalid: !timeValid(time),
				},
				className,
			)}
			value={time}
			placeholder='HH:mm'
			onInput={handleTimeInput}
		/>
	);
};

export default TimeInput;

// src/routes/fake-fitness-app/components/time-input.svelte
<script context="module" lang="ts">
	import dayjs from 'dayjs';
	import customParseFormat from 'dayjs/plugin/customParseFormat.js';

	dayjs.extend(customParseFormat);

	const timeAtLoad = dayjs().format('HH:mm');
</script>

<script lang="ts">
	import {timeValid, toTime} from '../util.ts';

	let className: string | undefined = undefined;
	export {className as class};
	export let time = timeAtLoad;
	export let width: string | undefined = undefined;

	function onInput(event: {currentTarget: HTMLInputElement}): void {
		const value = event.currentTarget.value;
		time = timeValid(value) ? toTime(value).format('HH:mm') : value;
	}
</script>

<input
	class="input-remove-input-visuals {className ?? ''}"
	class:invalid={!timeValid(time)}
	value={time}
	placeholder="HH:mm"
	on:input={onInput}
	style:width
/>
