// src/fake-fitness-app/components/time-overview.tsx
import clsx from 'clsx';
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';
import React, {useState} from 'react';

import * as CONSTS from '../scripts/consts';
import {
	calcDurationSecondsSinceMidnight,
	isValidDuration,
	midnight,
} from '../scripts/date-functions';

import '../styles/time-overview.scss';

dayjs.extend(customParseFormat);

const invalid = `invalid__${Math.random()}`;

const calcTimePerDistance = (distance: string, duration: string): string => {
	if (!isValidDuration(duration)) {
		return invalid;
	}

	if (!CONSTS.distanceRegex.test(distance)) {
		return invalid;
	}

	const parsedDistance = Number.parseFloat(distance);

	if (parsedDistance === 0) {
		// Avoid division by 0
		return '0\'00"';
	}

	const secondsSinceMidnight = calcDurationSecondsSinceMidnight(duration);

	if (secondsSinceMidnight === false) {
		return invalid;
	}

	const distancePerTime = secondsSinceMidnight / parsedDistance;

	const diff = midnight.add(distancePerTime, 's');

	// If hours is 0, don't display it
	return diff.get('h') === 0
		? diff.format('m\'ss"')
		: diff.format('H[h] m\'ss"');
};

const TimeOverview: React.FC<{
	setDuration: React.Dispatch<React.SetStateAction<string>>;
	setDistance: React.Dispatch<React.SetStateAction<string>>;
}> = ({setDuration: parentSetDuration, setDistance: parentSetDistance}) => {
	const [duration, setDuration] = useState(CONSTS.duration);
	const [distance, setDistance] = useState(CONSTS.distance);

	const timePerDistance = calcTimePerDistance(distance, duration);

	return (
		<div className='time-overview'>
			<div className='duration'>
				<input
					value={duration}
					className={clsx('input-remove-input-visuals', {
						invalid: !isValidDuration(duration),
					})}
					onInput={(event_): void => {
						const dur = event_.currentTarget.value.trim();
						setDuration(dur);
						parentSetDuration(dur);
					}}
				/>
			</div>
			<div className='distance'>
				<div>
					<input
						value={distance}
						className={clsx('input-remove-input-visuals', {
							invalid: !CONSTS.distanceRegex.test(distance.trim()),
						})}
						placeholder='0.00'
						onInput={(event_): void => {
							const distance = event_.currentTarget.value.trim();
							setDistance(distance);
							parentSetDistance(distance);
						}}
					/>
					<small>km</small>
				</div>
				<div className='vertical-border height-12' />
				<div
					className={clsx('time-per-distance', {
						invalid: timePerDistance === invalid,
					})}
				>
					{timePerDistance === invalid ? 'Invalid' : timePerDistance}
					<small>/km</small>
				</div>
			</div>
		</div>
	);
};

export default TimeOverview;

// src/routes/fake-fitness-app/components/time-overview.svelte
<script lang="ts">
	import dayjs from 'dayjs';
	import customParseFormat from 'dayjs/plugin/customParseFormat.js';

	import * as CONSTS from '../consts.ts';
	import {isValidDuration, calcTimePerDistance} from '../util.ts';

	dayjs.extend(customParseFormat);

	export let duration: string;
	export let distance: string;

	$: timePerDistance = calcTimePerDistance(distance, duration);
</script>

<div class="time-overview">
	<div class="duration">
		<input
			bind:value={duration}
			class="input-remove-input-visuals"
			class:invalid={!isValidDuration(duration)}
		/>
	</div>
	<div class="distance">
		<div>
			<input
				bind:value={distance}
				class="input-remove-input-visuals"
				class:invalid={!CONSTS.distanceRegex.test(distance)}
				placeholder="0.00"
			/><small>km</small>
		</div>
		<div class="vertical-border height-12" />
		<div class="time-per-distance" class:invalid={timePerDistance === false}>
			{timePerDistance === false ? 'Invalid' : timePerDistance}<small>/km</small
			>
		</div>
	</div>
</div>

<style>
	.time-overview {
		color: var(--text-white);

		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;

		background-color: var(--card-background);
		border-radius: var(--card-border-radius);
		margin-top: 20px;
		padding: 7vmin 0;
	}
	small {
		margin-left: 2px;
		font-size: 70%;
	}

	.duration {
		font: 1.9em Orbitron;
		display: flex;
		justify-content: center;
		align-items: center;
	}
	.duration input {
		width: 80%;
		text-align: center;
	}

	.distance {
		display: flex;
		justify-content: center;
		align-items: center;
		width: 80%;
	}

	.distance input {
		width: 6ch;
		display: inline;
		text-align: right;
		margin-right: 2px;
	}

	.distance .vertical-border {
		margin: 0 10px;
	}
</style>
