// src/quick-faker/components/modules/color.tsx
import {faker} from '@faker-js/faker';
import React from 'react';

import {Module} from '../module';

export const Color: React.FC = () => (
	<Module
		title='Color'
		module={faker.color}
		keys={[
			'cmyk',
			'colorByCSSColorSpace',
			'cssSupportedFunction',
			'cssSupportedSpace',
			'hsl',
			'human',
			'hwb',
			'lab',
			'lch',
			'rgb',
			'space',
		]}
	/>
);

// src/routes/quick-faker/components/modules/color.svelte
<script lang="ts">
	import {faker} from '@faker-js/faker';

	import Module from '../module.svelte';
</script>

<Module
	title="Color"
	module={faker.color}
	keys={[
		'cmyk',
		'colorByCSSColorSpace',
		'cssSupportedFunction',
		'cssSupportedSpace',
		'hsl',
		'human',
		'hwb',
		'lab',
		'lch',
		'rgb',
		'space',
	]}
/>
