// src/quick-faker/components/modules/company.tsx
import {faker} from '@faker-js/faker';
import React from 'react';

import {Module} from '../module';

export const Company: React.FC = () => (
	<Module
		title='Company'
		module={faker.company}
		keys={[
			'bs',
			'bsAdjective',
			'bsBuzz',
			'bsNoun',
			'catchPhrase',
			'catchPhraseAdjective',
			'catchPhraseDescriptor',
			'catchPhraseNoun',
			'companySuffix',
			'name',

			// Returns all suffixes
			// 'suffixes',

			// Deprecated
			// 'companyName',
		]}
	/>
);

// src/routes/quick-faker/components/modules/company.svelte
<script lang="ts">
	import {faker} from '@faker-js/faker';

	import Module from '../module.svelte';
</script>

<Module
	title="Company"
	module={faker.company}
	keys={[
		'bs',
		'bsAdjective',
		'bsBuzz',
		'bsNoun',
		'catchPhrase',
		'catchPhraseAdjective',
		'catchPhraseDescriptor',
		'catchPhraseNoun',
		'companySuffix',
		'name',

		// Returns all suffixes
		// 'suffixes',

		// Deprecated
		// 'companyName',
	]}
/>
