// src/quick-faker/components/modules/datatype.tsx
import {faker} from '@faker-js/faker';
import React from 'react';

import {Module} from '../module';

export const Datatype: React.FC = () => (
	<Module
		title='Datatype'
		module={faker.datatype}
		keys={[
			'array',
			'bigInt',
			'boolean',
			'datetime',
			'float',
			'hexadecimal',
			'json',
			'number',
			'string',
			'uuid',
		]}
	/>
);

// src/routes/quick-faker/components/modules/datatype.svelte
<script lang="ts">
	import {faker} from '@faker-js/faker';

	import Module from '../module.svelte';
</script>

<Module
	title="Datatype"
	module={faker.datatype}
	keys={[
		'array',
		'bigInt',
		'boolean',
		'datetime',
		'float',
		'hexadecimal',
		'json',
		'number',
		'string',
		'uuid',
	]}
/>
